version: '3.8'

services:
  mongodb-auth:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ravuser
      MONGO_INITDB_ROOT_PASSWORD: ravpass
      MONGO_INITDB_DATABASE: ravrunner
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data: